mailer: import 'aiosmtplib' and 'html2text' lazily
plone/guillotina pull request #1007
Opened 2020-09-23 13:45 UTC by masipcat

I'm using a custom MailerEndpoint based on aiobotocore so I don't need the aiosmtp and I don't use the html2text as well

2020-09-23 14:37 UTC, vangheem approved these changes

2020-09-23 16:29 UTC, bloodbare commented
@masipcat would not be better to define a try except of import modules. They way its implemented each time you go on that code will load the library

2020-09-23 16:29 UTC, bloodbare requested changes
Try except import instead of local loading

2020-09-23 16:34 UTC, masipcat commented
I think it's only imported the first time is called, not at every function call, but I can change it

2020-09-24 06:33 UTC, bloodbare approved these changes

2020-09-24 06:35 UTC, merged