Fix metrics missing variable
plone/guillotina pull request #1058
Opened 2020-12-04 20:51 UTC by masipcat

2020-12-04 21:01 UTC, bloodbare commented on guillotina/db/storages/pg.py
> +    class watch:
This can also be metics.watch because Counter will be None, no ?

2020-12-04 21:01 UTC, vangheem requested changes
maybe not none check instead?

2020-12-04 21:01 UTC, vangheem commented on guillotina/metrics.py
> +        if self.histogram:
```suggestion
        if self.histogram is not None:
```

2020-12-05 01:26 UTC, vangheem approved these changes

2020-12-05 19:51 UTC, bloodbare approved these changes

2020-12-05 19:51 UTC, merged