Use asyncio.run to run commands
plone/guillotina pull request #1125
Opened 2021-04-27 11:18 UTC by masipcat

The motivation behind this change is to fix https://github.com/plone/guillotina_elasticsearch/pull/86.

2021-04-27 11:21 UTC, masipcat commented on guillotina/commands/__init__.py
> +        pass
I think this wasn't needed in the past because of the `sys.exit(0)`

2021-04-27 12:48 UTC, vangheem approved these changes

2021-04-28 18:40 UTC, bloodbare requested changes
Which is the reason to change to asyncio.run ? this does not allow to set the loop, we should change the api to not receive a loop as it can not be set on asyncio.run.

2021-04-28 18:51 UTC, masipcat commented
> Which is the reason to change to asyncio.run ? this does not allow to set the loop, we should change the api to not receive a loop as it can not be set on asyncio.run.

I didn't know we wanted to be able to change the loop and asyncio.run "just works". In fact, it takes care of some thing during the shutdown that we are not doing, and it seemed cleaner to use this function. I'm curious, which's the usecase to change the loop?

2021-04-28 18:56 UTC, masipcat commented
Now I realize that maybe the PR title it's not accurate to the intention of this PR. The important change is that now it's "asyncio-first": all the startup, main, and shutodown logic runs inside the loop.

This can be accomplished as well without using asyncio.run, and I can change it if we need to be able to change the loop

2021-04-28 18:58 UTC, bloodbare commented
> Now I realize that maybe the PR title it's not accurate to the intention of this PR. The important change is that now it's "asyncio-first": all the startup, main, and shutodown logic runs inside the loop.
> 
> This can be accomplished as well without using asyncio.run, and I can change it if we need to be able to change the loop

The use case for reusing the loop its to overwrite Command class on a class that calls multiple commands or on tests environments. In any case the contract has loop as parameter and now its not used at any place.

2021-04-28 19:01 UTC, bloodbare commented
> Now I realize that maybe the PR title it's not accurate to the intention of this PR. The important change is that now it's "asyncio-first": all the startup, main, and shutodown logic runs inside the loop.
> 
> This can be accomplished as well without using asyncio.run, and I can change it if we need to be able to change the loop

I feel ok to have the main run as async, its a change on API which will breake some code, so it should not be a bugfix release, no ?

2021-04-29 10:22 UTC, masipcat commented
> I feel ok to have the main run as async, its a change on API which will breake some code, so it should not be a bugfix release, no ?

The PR is till backwards compatible with commands with non-async run functions. But if we feel this case can be removed, I can delete the code and change the minor number

2021-04-30 10:18 UTC, bloodbare approved these changes

2021-04-30 10:18 UTC, merged