Set id/name of group to ease the access later via id/name
plone/guillotina pull request #1156
Opened 2021-11-06 08:27 UTC by ksuess

POST /db/todo/groups HTTP/1.1
Accept: application/json
Authorization: Basic cm9vdDpyb290
Content-Type: application/json
Host: localhost:8080

{
    "@type": "Group",
    "name": "todo_viewer"
}

leads to a generated id/name

Set also title

2021-11-10 11:02 UTC, nilbacardit26 commented
Hi @ksuess, thank you for the PR, we appreciate that!

You need to change as well the next lines:

```
HTTP/1.1 201 Created
    Content-Type: application/json
    Location: http://localhost:8080/db/todo/groups/14f624ef23094362961df0e083cd77e4
```
by:
```
HTTP/1.1 201 Created
    Content-Type: application/json
    Location: http://localhost:8080/db/todo/groups/todo_viewer
```

2021-11-10 11:03 UTC, nilbacardit26 requested changes
The next lines after the POST, need to be changed by the id of the group

2021-11-10 19:24 UTC, bloodbare commented
Could you rebase to master, there was a problem on black

2021-11-22 08:22 UTC, nilbacardit26 approved these changes

2021-11-22 19:43 UTC, bloodbare approved these changes

2021-11-22 19:43 UTC, merged